apiVersion: v1
kind: Pod
metadata:
  name: k8sj
  namespace: front-end
spec:
  containers:
  - name: k8sj
    image: k8sj
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
      name: k8sjport